# Google Colab

Visite el siguiente video como introducción a Google Colaboratory. Recuerde **activar subtítulos** en español de Latinoamérica.

[Get started with Google Colaboratory (~3min.)](https://www.youtube.com/watch?v=inN8seMm7UI)

# 5 Pilas, Colas y Colas de Prioridad

En este capítulo veremos tres _tipos de datos abstractos_ (_TDAs_) que son muy utilizados.

Un tipo de datos abstracto es un conjunto de datos, más operaciones asociadas, para el cual se aplica una política de "ocultamiento de información": los usuarios del TDA saben **qué** funcionalidad éste provee, pero no saben **cómo** se implementa esta funcionalidad.

Esta separación de responsabilidad es fundamental para mantener la complejidad bajo control.
Sólo los implementadores del TDA necesitan preocuparse de su implementación, y además son libres para modificarla en la medida que la interfaz de uso se mantenga intacta.

## Pilas ("*Stacks*")

Una **pila**, también llamada *stack* o *pushdown* en inglés, es una lista de elementos en la cual todas las operaciones se realizan solo en un extremo de la lista.

Es usual visualizar la pila creciendo verticalmente hacia arriba, y llamamos "tope" a su extremo superior:

![pila](https://github.com/ppoblete/AED/blob/master/pila.png?raw=1)

Las dos operaciones básicas son **push** (apilar), que agrega un elemento encima de todos, y **pop** (desapilar), que extrae el elemento del tope de la pila. Más precisamente, si `s` es un objeto de tipo Pila, están disponibles las siguientes operaciones:

* `s.push(x)`: apila x en el tope de la pila `s`
* `x=s.pop()`: extrae y retorna el elemento del tope de la pila `s`
* `b=s.is_empty()`: retorna verdadero si la pila `s` está vacía, falso si no

Dado que los elementos salen de la pila en el orden inverso en que ingresaron, esta estructura también se conoce como "lista LIFO", por "Last-In-First-Out".

### Implementación usando listas de Python

Es posible implementar una pila muy fácilmente usando las listas que provee el lenguaje Python:

In [ ]:
class Pila:
    def __init__(self):
        self.s=[]
    def push(self,x):
        self.s.append(x)
    def pop(self):
        assert len(self.s)>0
        return self.s.pop() # pop de lista, no de Pila
    def is_empty(self):
        return len(self.s)==0

In [ ]:
a=Pila()
a.push(10)
a.push(20)
print(a.pop())
a.push(30)
print(a.pop())
print(a.pop())

20
30
10


Esta implementación simple posiblemente sirve en la mayoría de los casos, pero si necesitamos poder garantizar su eficiencia, tenemos el problema que la implementación de las listas de Python está fuera de nuestro control, y no podemos garantizar, por ejemplo, que cada una de las operaciones tome tiempo constante.

Por ese motivo, es útil contar con implementaciones en que sí podamos dar ese tipo de garantía.

### Numpy y Arreglos

Numpy es la principal biblioteca para computación científica en Python.

Una de las características de Numpy es que provee arreglos multidimensionales de alta eficiencia. Mientras la gran flexibilidad de las listas de Python puede hacer que no sea muy eficiente el acceso a elementos específicos, los arreglos de Numpy aseguran el acceso a cada elemento en tiempo constante. Por esa razón, utilizaremos estos arreglos cuando necesitemos asegurar la eficiencia de la implementación de los algoritmos.

In [ ]:
import numpy as np

a = np.array([6.5, 5.2, 4.6, 7.0, 4.3])
print(a[2])

4.6


In [ ]:
print(len(a))

5


Hay varias formas de crear arreglos inicializados con ceros, unos, valores constantes o valores aleatorios.

In [ ]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
c = np.zeros(7,dtype=int)
print(c)

[0 0 0 0 0 0 0]


En los dos ejemplos anteriores mostramos la diferencia que se produce al explicitar el tipo de datos del arreglo. En el primero, obtenemos el *default*, que es flotante, mientras en el segundo forzamos a que sea entero.

In [ ]:
c = np.full(5, 2)
print(c)

[2 2 2 2 2]


In [ ]:
d = np.random.random(6)
print(d)

[0.35640065 0.09732194 0.02349796 0.46170343 0.06758907 0.24967954]


También es posible crear y manejar arreglos de varias dimensiones.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
(m,n)=np.shape(a)
print(m,n)

2 3


In [ ]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Implementación de una pila usando un arreglo

Utilizaremos un arreglo $s$, en donde los elementos de la pila se almacenarán en los casilleros $0,1,\ldots$, con el elemento del tope en el casillero ocupado de más a la derecha. Mantendremos una variable $n$ para almacenar el número de elementos presentes en la pila, y el arreglo tendrá un tamaño máximo, el que se podrá especificar opcionalmente al momento de crear la pila.

![pila-arreglo](https://github.com/ppoblete/AED/blob/master/pila-arreglo.png?raw=1)

In [ ]:
import numpy as np

class Pila:
    def __init__(self,maxn=100):
        self.s=np.zeros(maxn)
        self.n=0
    def push(self,x):
        assert self.n<len(self.s)-1
        self.s[self.n]=x
        self.n+=1
    def pop(self):
        assert self.n>0
        self.n-=1
        return self.s[self.n]
    def is_empty(self):
        return self.n==0
a=Pila() 
a.push(10) 
a.push(20)
print(a.is_empty())
print(a.pop()) 
a.push(30) 
print(a.pop()) 
print(a.pop())
print(a.is_empty())

False
20.0
30.0
10.0
True


### Implementación usando una lista enlazada

En esta implementación los elementos de la pila se almacenan en una lista de enlace simple (sin cabecera), en que el elemento del tope de la pila es el primero de la lista.

![pila-lista](https://github.com/ppoblete/AED/blob/master/pila-lista.png?raw=1)

In [ ]:
class NodoLista:
    def __init__(self,info,sgte=None):
        self.info=info
        self.sgte=sgte
class Pila:
    def __init__(self):
        self.tope=None
    def push(self,x):
        self.tope=NodoLista(x,self.tope)
    def pop(self):
        assert self.tope is not None
        x=self.tope.info
        self.tope=self.tope.sgte
        return x
    def is_empty(self):
        return self.tope is None

In [ ]:
a=Pila()
a.push(10)
a.push(20)
print(a.pop())
a.push(30)
print(a.pop())
print(a.pop())

20
30
10


### Aplicaciones de pilas

#### Evaluación de balanceo de paréntesis en expresiones matemáticas

En cualquier expresión aritmética que haga uso de paréntesis es necesario que estas estén balanceadas, es decir, para cada paréntesis que se abra debe haber una que la cierre. De ser así decimos que los paréntesis de la expresión están *balanceados*.

Ej:
1. ((1+5)+4*3)) no tiene las paréntesis balanceadas.
2. ((1+5)+4*3) sí las tiene balanceadas.
3. [(4+5+9+10)*5]+20*(4+40) sí las tiene balanceadas.
4. [[(4+5+9+10)*5]+20*(4+40)) no las tiene balanceadas.

Para solucionar este problema podemos usar una pila haciendo `push` a cada paréntesis de apertura y `pop` a cada paréntesis que cierra.

In [ ]:
def estaBalanceada(exp):
  abren="[{("
  cierran="]})"
  pila = Pila()

  for c in exp:
    if c in abren:
      pila.push(c)
    elif c in cierran:
      if pila.is_empty():
        return False
      x=pila.pop() # sacamos el paréntesis que abre
     
      # si NO corresponden la de la apertura con la de cierre: False

      if x == "[" and c !="]":
        return False
      elif x == "(" and c !=")":
        return False
      elif x == "{" and c !="}":
        return False

  if pila.is_empty():
    return True
  else:
    return False

print(estaBalanceada("((1+5)+4*3))"))
print(estaBalanceada("((1+5)+4*3)"))
print(estaBalanceada("[(4+5+9+10)5]+20(4+40)"))
print(estaBalanceada("[[(4+5+9+10)5]+20(4+40))"))



False
True
True
False


## Colas ("*Queues*")

Una cola es una lista en que los elementos ingresan por un extremo y salen por el otro. Debido a que los elementos van saliendo en orden de llegada, una cola también se llama "lista FIFO", por "First-In-First-Out".

![cola](https://github.com/ppoblete/AED/blob/master/cola.png?raw=1)

Las dos operaciones básicas son **enq** (encolar), que agrega un elemento al final de todos, y **deq** (desencolar), que extrae el elemento que encabeza la cola. Más precisamente, si `q` es un objeto de tipo Cola, están disponibles las siguientes operaciones:

* `q.enq(x)`: encola x al final de la cola `q`
* `x=q.deq()`: extrae y retorna el elemento a la cabeza de la cola `q`
* `b=q.is_empty()`: retorna verdadero si la cola `q`está vacía, falso si no

### Implementación usando listas de Python

Tal como hicimos en el caso de las pilas, es muy simple implementar colas usando las listas de Python, pero no tenemos mucho control sobre la eficiencia del resultado:

In [ ]:
class Cola:
    def __init__(self):
        self.q=[]
    def enq(self,x):
        self.q.insert(0,x)
    def deq(self):
        assert len(self.q)>0
        return self.q.pop()
    def is_empty(self):
        return len(self.q)==0

In [ ]:
a=Cola()
a.enq(72)
a.enq(36)
print(a.deq())
a.enq(20)
print(a.deq())
print(a.deq())
a.enq(61)
print(a.deq())

72
36
20
61


### Implementación usando un arreglo

De manera análoga a lo que hicimos en el caso de la pila, podemos almacenar los $n$ elementos de la cola usando posiciones contiguas en un arreglo, por ejemplo, las $n$ primeras posiciones.
Pero hay un problema: como la cola crece por un extremo y se achica por el otro, ese grupo de posiciones contiguas se va desplazando dentro del arreglo, y después de un rato choca contra el otro extremo. La solución es ver al arreglo como _circular_, esto es, que si el arreglo tiene tamaño $maxn$, a continuación de la posición $maxn-1$ viene la posición $0$. Esto se puede hacer fácilmente usando aritmética módulo $maxn$.

Para la implementación, utilizaremos un subíndice $cabeza$ que apunta al primer elemento de la cola, y una variable $n$ que indica cuántos elementos hay en la cola.
La siguiente figura muestra dos situaciones en que podría encontrarse el arreglo:

![cola-arreglo](https://github.com/ppoblete/AED/blob/master/cola-arreglo.png?raw=1)

In [ ]:
import numpy as np
class Cola:  
    def __init__(self,maxn=100):
        self.q=np.zeros(maxn,dtype=int)
        self.n=0
        self.cabeza=0
    def enq(self,x):
        assert self.n<len(self.q)-1
        self.q[(self.cabeza+self.n)%len(self.q)]=x
        self.n+=1      
    def deq(self):
        assert self.n>0
        x=self.q[self.cabeza]
        self.cabeza=(self.cabeza+1)%len(self.q)
        self.n-=1
        return x
    def is_empty(self):
        return self.n==0

In [ ]:
a=Cola(3) # para forzar circularidad
a.enq(72)
a.enq(36)
print(a.deq())
a.enq(20)
print(a.deq())
print(a.deq())
a.enq(61)
print(a.deq())

72
36
20
61


### Implementación usando una lista enlazada

El operar en los dos extremos de la cola sugiere de inmediato el uso de una lista de doble enlace, y esa es una opción posible. Pero, como veremos, se puede implementar una cola con una lista de enlace simple:

![cola-lista](https://github.com/ppoblete/AED/blob/master/cola-lista.png?raw=1)

Una cosa que complica un poco la programación es que el invariante que se ve a la derecha se cumple solo si la cola es no vacía. Para una cola vacía, los dos punteros (primero y último) son nulos. Por lo tanto, un `enq` sobre una cola vacía, y un `deq` que deja una cola vacía serán casos especiales.

In [ ]:
class NodoLista:
    def __init__(self,info,sgte=None):
        self.info=info
        self.sgte=sgte
class Cola:
    def __init__(self):
        self.primero=None
        self.ultimo=None
    def enq(self,x):
        p=NodoLista(x)
        if self.ultimo is not None: # cola no vacía, agregamos al final
            self.ultimo.sgte=p
            self.ultimo=p
        else: # la cola estaba vacía
            self.primero=p
            self.ultimo=p
    def deq(self):
        assert self.primero is not None
        x=self.primero.info
        if self.primero is not self.ultimo: # hay más de 1 elemento
            self.primero=self.primero.sgte
        else: # hay solo 1 elemento, el deq deja la cola vacía
            self.primero=None
            self.ultimo=None
        return x
    def is_empty(self):
        return self.primero is None

In [ ]:
a=Cola()
a.enq(72)
a.enq(36)
print(a.deq())
a.enq(20)
print(a.deq())
print(a.is_empty())
print(a.deq())
print(a.is_empty())
a.enq(61)
print(a.deq())
print(a.is_empty())

72
36
False
20
True
61
True


### Aplicaciones de colas

Las colas se utilizan en los sistemas operativos siempre que hay algún recurso que no puede ser compartido. Uno de los procesos que lo requieren tiene acceso al recurso, mientras los demás deben esperar en una cola. Un ejemplo de esto son los sistemas de "spooling" para las impresoras.

También se usan mucho en sistemas de simulación, cuando se deben modelar situaciones del mundo real en que hay colas. Por ejemplo, la caja en un supermercado.


### Ejercicio: simulación de una cola de supermercado

Codifique en Python un programa que simule una cola de Supermercado. Cada persona esté representada por su nombre de pila (Ej: “Alicia”). Para ello debe utilizar una Cola y los servicios que esta ofrece: `push`, `pop` e `is_empty`. A continuación un ejemplo del diálogo del programa:

```
Cola de Supermercado.
Ingrese “+<nombre>” si desea agregar <nombre> a la Cola y “-“ si desea sacar al primero de la cola.
Cola vacía
? +Alicia
1 persona en cola
? +Pedro
2 personas en cola
? -
Sale Alicia. 1 persona en la cola
? +Andres
2 personas en la cola
? -
Sale Pedro. 1 persona en la cola
? -
Sale Andres
Cola vacia
? fin (Termina el programa)
```

Codifique la solución a este problema. Una vez terminado, enviélo al correo del o de la profesor(a). Se ofrecen 3 décimas para el siguiente taller a quienes entreguen de forma individual el código antes de la siguiente clase.