## Numpy y Arreglos

Numpy es la principal biblioteca para computación científica en Python.

Una de las características de Numpy es que provee arreglos multidimensionales de alta eficiencia. Mientras la gran flexibilidad de las listas de Python puede hacer que no sea muy eficiente el acceso a elementos específicos, los arreglos de Numpy aseguran el acceso a cada elemento en tiempo constante. Por esa razón, utilizaremos estos arreglos cuando necesitemos asegurar la eficiencia de la implementación de los algoritmos.


In [ ]:
import numpy as np

a = np.array([6.5, 5.2, 4.6, 7.0, 4.3])
print(a[2])

4.6


In [ ]:
print(len(a))

5


Hay varias formas de crear arreglos inicializados con ceros, unos, valores constantes o valores aleatorios.

In [ ]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
c = np.zeros(7,dtype=int)
print(c)

[0 0 0 0 0 0 0]


En los dos ejemplos anteriores mostramos la diferencia que se produce al explicitar el tipo de datos del arreglo. En el primero, obtenemos el *default*, que es flotante, mientras en el segundo forzamos a que sea entero.

In [ ]:
c = np.full(5, 2)
print(c)

[2 2 2 2 2]


In [ ]:
d = np.random.random(6)
print(d)

[0.39229597 0.99294597 0.16978406 0.49579816 0.3654721  0.43266937]


También es posible crear y manejar arreglos de varias dimensiones.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a[0,2])

3


In [ ]:
(m,n)=np.shape(a)
print(m,n)

2 3


In [ ]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
